# One Dimensional Numpy

In [1]:
# import numpy library
import numpy as np

In [2]:
# create a numpy array

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
# numpy version
print(np.__version__)

2.0.1


In [4]:
# Check the type of the array
type(a)

numpy.ndarray

In [5]:
# Check the type of the values stored in numpy array
a.dtype

dtype('int64')

**Slicing**

In [7]:
# Slicing the numpy array

d = a[1:3]
d

array([2, 3])

In [9]:
# Set the fourth element and fifth element to 300 and 400
a[3:5] = '300', '400'
a

array([  1,   2,   3, 300, 400])

**Assign Value with List**

In [13]:
# Create the index list

s = [5,6,7,8]
s

[5, 6, 7, 8]

In [15]:
# Get the size of numpy array

a.size

5

In [16]:
# Get the number of dimensions of numpy array

a.ndim

1

In [17]:
# Get the shape/size of numpy array

a.shape

(5,)

# Numpy Statistical Functions

In [19]:
# Create a numpy array

a = np.array([1,4,6,7,8])
a

array([1, 4, 6, 7, 8])

In [20]:
# Get the mean of numpy array

mean = a.mean()
mean

np.float64(5.2)

In [21]:
# Get the standard deviation of numpy array

standard_deviation = a.std()
standard_deviation

np.float64(2.4819347291981715)

In [22]:
# Get the smallest value in the numpy array

min = a.min()
min

np.int64(1)

# Numpy Array Operations

**Array Addition**

In [27]:
u = np.array([1,0])
u

array([1, 0])

In [28]:
v = np.array([0,1])
v

array([0, 1])

In [33]:
# Numpy Array Addition

add = np.add(u,v)
add

array([1, 1])

**Array Subtraction**

In [39]:
a = np.array([7,4])
b = np.array([2,6])

In [40]:
sub = np.subtract(a,b)
sub

array([ 5, -2])

**Array Multiplication**

In [41]:
a = np.array([3,9])
b = np.array([6,7])

In [42]:
mul = np.multiply(a,b)
mul

array([18, 63])

**Array Division**

In [43]:
a = np.array([10,20,30])
b = np.array([5,4,3])


In [44]:
div = np.divide(a,b)
div

array([ 2.,  5., 10.])