In [1]:
# import numpy library
import numpy as np

In [2]:
# create a numpy array

a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [3]:
# numpy version
print(np.__version__)

2.0.1


In [4]:
# Check the type of the array
type(a)

numpy.ndarray

In [5]:
# Check the type of the values stored in numpy array
a.dtype

dtype('int64')

**Slicing**

In [7]:
# Slicing the numpy array

d = a[1:3]
d

array([2, 3])

In [9]:
# Set the fourth element and fifth element to 300 and 400
a[3:5] = '300', '400'
a

array([  1,   2,   3, 300, 400])

**Assign Value with List**

In [13]:
# Create the index list

s = [5,6,7,8]
s

[5, 6, 7, 8]

In [15]:
# Get the size of numpy array

a.size

5

In [16]:
# Get the number of dimensions of numpy array

a.ndim

1

In [17]:
# Get the shape/size of numpy array

a.shape

(5,)