# 2D Numpy

**Create a 2D Numpy Array**

In [2]:
# Import the libraries

import numpy as np

In [2]:
# Create a list

a = [1,2,3], [4,5,6], [7,8,9]
a

([1, 2, 3], [4, 5, 6], [7, 8, 9])

In [3]:

A = np.array(a)
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# Show the numpy array dimensions
A.ndim

2

In [5]:
# Show the numpy array shape
A.shape

(3, 3)

In [6]:
# Show the numpy array size
A.size

9

**Accessing different elements of a Numpy Array**

In [7]:
# Access the element on the second row and third column

A[1, 2]

np.int64(6)

In [10]:
A[2][0]

np.int64(7)

# Basic Operations

In [8]:
x = np.array([ [2,5] , [5,6]])
y = np.array([ [3,1] , [9,7]])

In [14]:
#Addition

z = x + y
z

array([[ 5,  6],
       [14, 13]])

In [10]:
# Multiply Y with 2

z = 2 * x
z

array([[ 4, 10],
       [10, 12]])

In [11]:
z = x*y
z

array([[ 6,  5],
       [45, 42]])

# Matrix Multiplication

**Cross Product**

In [12]:
# Create a matrix A

A = np.array([[1,4,6], [3,2,7]])
A

array([[1, 4, 6],
       [3, 2, 7]])

In [13]:
# Create a matrix B

B = np.array([[3,4,1], [5,9,3]])
B

array([[3, 4, 1],
       [5, 9, 3]])

In [18]:
# Calculate the Cross product

cross = np.cross(A,B)
cross

array([[-20,  17,  -8],
       [-57,  26,  17]])

**Dot Product**

In [22]:
# Create a matrix A

X = np.array([[0, 1, 1], [1, 0, 1]])
X

array([[0, 1, 1],
       [1, 0, 1]])

In [23]:
# Create a matrix B

Y = np.array([[1, 1], [1, 1], [-1, 1]])
Y

array([[ 1,  1],
       [ 1,  1],
       [-1,  1]])

In [24]:
# Calculate the Cross product

dot = np.dot(X,Y)
dot

array([[0, 2],
       [0, 2]])

In [25]:
# Calculate the sine of Z

sin = np.sin(dot)
sin

array([[0.        , 0.90929743],
       [0.        , 0.90929743]])

In [26]:
#Transpose

# Create a matrix C

C = np.array([[1,1],[2,2],[3,3]])
C

# Get the transposed of C
C.T

array([[1, 2, 3],
       [1, 2, 3]])